name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - run: yarn --frozen-lockfile
      - run: yarn run lint:eslint
      - run: yarn run lint:prettier
      - run: yarn run typecheck
